title: McClean Leads Blog
email: 
description: >- # this means to ignore newlines until "baseurl:"
  This is where I blog about entertaining insights.
baseurl: "" # the subpath of your site, e.g., "/blog"
url: "http://mccleanleads.com" # the base hostname & protocol for your site
twitter_username: @TheCanaanMcGee
github_username:  

# Build settings
theme: minima
plugins:
  - jekyll-feed
