title: The McGee Letter
description: >- # this means to ignore newlines until "baseurl:"
  This is where you get entertaining insights about business and life.
baseurl: "/blog" # the subpath of your site, e.g., "/blog"
url: "http://mccleanleads.com" # the base hostname & protocol for your site
twitter_username: "TheCanaanMcGee"

# Build settings
theme: minima
plugins:
  - jekyll-feed
